version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongoDB
    volumes:
      - .:/usr/src/app/

  mongoDB:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
